### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" using next.js

### ISSUE THREAD

**Issue by YannickLehr** [sametweb/react-step-builder#28]
Using it with next.js will create the following error while rendering: 
**Server Error
SyntaxError: Cannot use import statement outside a module
This error happened while generating the page. Any console logs will be displayed in the terminal window.**

`> 1 | module.exports = require("react-step-builder");`

**Comment by sametweb** [comment]
Hello Yannick,

I haven't tested in a Next.js application. I will look into this problem and try to solve it. Also, if you'd like to take a stab at it, please feel free to do so.

**Comment by aliabdy** [comment]
@YannickLehr @sametweb 
This is fixed with dynamic import : 

`const  Steps = dynamic(import('react-step-builder').then(mod => mod.Steps), {ssr: false});`
`const  Step  = dynamic<any>(import('react-step-builder').then(mod => mod.Step), {ssr: false});`

**Comment by sametweb** [comment]
@aliabdy Thank you for the solution! Would you like to add this usage to the README file?

**Comment by ninearif** [comment]
> Hello Yannick,
> 
> I haven't tested in a Next.js application. I will look into this problem and try to solve it. Also, if you'd like to take a stab at it, please feel free to do so.

IYour package on npm written as ES Module (ESM),
Next.js have a server-side that runs on node.js, I guess it's use webpack and load the modules with CommonJS (CJS) loader.
so it's not compatible with your ESM package, that's why the error occurred.

A better solution is to build it to support multiple modules (ESM, CJS, etc.), you can make your npm package compatible with both React and Next.js or many JS projects, so the library users can use it with no need to do any additional configuration or workaround.
**no need to rewrite the code, 
just add some Babel building configuration, edit some attributes in your package.json

here is some information that might help you.
https://dev.to/remshams/rolling-up-a-multi-module-system-esm-cjs-compatible-npm-library-with-typescript-and-babel-3gjg

**Comment by sametweb** [comment]
I am accepting @aliabdy 's solution for a temporary fix for now and closing the issue.

**Comment by sametweb** [comment]
> > Hello Yannick,
> > I haven't tested in a Next.js application. I will look into this problem and try to solve it. Also, if you'd like to take a stab at it, please feel free to do so.
> 
> Your package on npm written as ES Module (ESM),
> Next.js have a server-side that runs on node.js, I guess it's use webpack and load the modules with CommonJS (CJS) loader.
> so it's not compatible with your ESM package, that's why the error occurred.
> 
> A better solution is to build it to support multiple modules (ESM, CJS, etc.), you can make your npm package compatible with both React and Next.js, so the library users can use it with no need to do any additional configuration or workaround.
> 
> > no need to rewrite the code,
> > just add some Babel building configuration, and edit some attributes in your package.json
> 
> here is some information that might help you.
> https://dev.to/remshams/rolling-up-a-multi-module-system-esm-cjs-compatible-npm-library-with-typescript-and-babel-3gjg

I did publish a beta version as a fix to this problem. The solution is pretty much what you explained here. I hope it helps!
